# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('chat_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('name', models.CharField(help_text='Enter a delivery name', max_length=40, primary_key=True, serialize=False)),
                ('chat_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ChatInfo')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTypes',
            fields=[
                ('name', models.CharField(help_text='Enter a delivery type name', max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_path', models.TextField()),
                ('file_id', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='deliveries',
            name='dtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.DeliveryTypes'),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Images'),
        ),
    ]
